---
image: docker:latest

# Change pip's cache directory to be inside the project directory since we can
# only cache local items.
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache"

# Pip's cache doesn't store the python packages
# https://pip.pypa.io/en/stable/reference/pip_install/#caching
#
# If you want to also cache the installed packages, you have to install
# them in a virtualenv and cache it as well.
cache:
  paths:
    - .cache/pip

# Define the available CI stages
stages:
  # check format of project files
  - lint

  # build the project and documentation
  - build

  # test the application
  - test

  # deploy the application, send to GitHub, PyPi and/or DockerHub
  - deploy


# Lint our Markdown files as part of the verify stage
markdownlint:
  stage: lint
  tags:
    - lint
  image:
    name: ruby:alpine
    entrypoint: [""]
  before_script:
    - gem install mdl
    - mdl --version
  script:
    - mdl --style mdl_style.rb --warnings .

# Lint our YAML files as part of the verify stage
yamllint:
  stage: lint
  tags:
    - lint
  image: sdesbure/yamllint
  before_script:
    - yamllint --version
  script:
    - yamllint .
